<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>InnoClinic.ServiceApi.BusinessLogic</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\InnoClinic.Shared\InnoClinic.Shared.csproj" />
      <ProjectReference Include="..\InnoClinic.ServiceApi.DAL\InnoClinic.ServiceApi.DAL.csproj" />
    </ItemGroup>

</Project>
